window.ECHO_QUESTIONS = [
  // 机场：值机与托运（连续场景 1/2）
  { scene: "机场 · 值机柜台", turn: "1/6", speaker: "Staff", context: "Good morning. Where are you flying today?", cn: "我要飞往温哥华。", en: "I am flying to Vancouver.", alts: ["I am going to Vancouver."], category: "机场通关", tag: "值机 · 说明目的地" },
  { scene: "机场 · 值机柜台", turn: "2/6", speaker: "Staff", context: "May I see your passport, please?", cn: "当然，给您。", en: "Of course. Here you are.", alts: ["Sure. Here you go."], category: "机场通关", tag: "递交证件 · 自然回应" },
  { scene: "机场 · 值机柜台", turn: "3/6", speaker: "Staff", context: "Do you have any bags to check?", cn: "有，我想托运这个行李箱。", en: "Yes, I would like to check this suitcase.", alts: ["Yes, I want to check this bag."], category: "机场通关", tag: "托运行李 · check a bag" },
  { scene: "机场 · 值机柜台", turn: "4/6", speaker: "Staff", context: "Would you prefer a window or an aisle seat?", cn: "如果可以的话，我想要靠过道的座位。", en: "I would prefer an aisle seat, if possible.", alts: ["An aisle seat, please, if possible."], category: "机场通关", tag: "选座 · if possible" },
  { scene: "机场 · 值机柜台", turn: "5/6", speaker: "Staff", context: "Your bag is two kilos overweight.", cn: "额外的行李费是多少？", en: "How much is the extra baggage fee?", alts: ["How much do I need to pay for the extra baggage?"], category: "机场通关", tag: "超重行李 · 询问费用" },
  { scene: "机场 · 值机柜台", turn: "6/6", speaker: "Staff", context: "Here is your boarding pass. Boarding starts at 8:20.", cn: "请问登机口在哪里？", en: "Could you tell me where the boarding gate is?", alts: ["Where is the boarding gate, please?"], category: "机场通关", tag: "登机口 · 间接疑问句" },

  // 机场：安检、入境与转机（连续场景 2/2）
  { scene: "机场 · 安检", turn: "1/6", speaker: "Officer", context: "Please place your electronics in a separate tray.", cn: "我的相机也需要拿出来吗？", en: "Do I need to take out my camera as well?", alts: ["Should I take my camera out too?"], category: "机场通关", tag: "安检 · need to" },
  { scene: "机场 · 安检", turn: "2/6", speaker: "Officer", context: "Is there any liquid in your bag?", cn: "只有一个小瓶子，不到一百毫升。", en: "Just a small bottle. It is under one hundred milliliters.", alts: ["Only a small bottle. It is less than one hundred milliliters."], category: "机场通关", tag: "安检液体 · 数量说明" },
  { scene: "机场 · 入境柜台", turn: "3/6", speaker: "Officer", context: "What is the purpose of your visit?", cn: "我来这里度假，会待十天。", en: "I am here on vacation and I will stay for ten days.", alts: ["I am here for a holiday and will be staying for ten days."], category: "机场通关", tag: "入境回答 · 旅行目的" },
  { scene: "机场 · 入境柜台", turn: "4/6", speaker: "Officer", context: "Where will you be staying?", cn: "我会住在市中心的一家酒店。", en: "I will be staying at a hotel downtown.", alts: ["I am staying at a hotel in the city center."], category: "机场通关", tag: "入境回答 · 住宿信息" },
  { scene: "机场 · 转机服务台", turn: "5/6", speaker: "You", context: "Your first flight was delayed and your connection is very tight.", cn: "我可能赶不上转机，您能帮我吗？", en: "I might miss my connecting flight. Could you help me?", alts: ["I may miss my connection. Can you help me?"], category: "机场通关", tag: "转机 · 寻求帮助" },
  { scene: "机场 · 行李查询", turn: "6/6", speaker: "Staff", context: "What does your missing bag look like?", cn: "它是一个黑色的中号行李箱。", en: "It is a medium-sized black suitcase.", alts: ["It is a black medium-sized suitcase."], category: "机场通关", tag: "行李丢失 · 描述物品" },

  // 城市交通：地铁、公交与出租车
  { scene: "城市 · 地铁站", turn: "1/6", speaker: "You", context: "You are looking at the ticket machine but cannot find your destination.", cn: "请问去市中心应该坐哪条线？", en: "Which line should I take to get downtown?", alts: ["Which subway line goes to the city center?"], category: "交通问路", tag: "地铁问路 · which line" },
  { scene: "城市 · 地铁站", turn: "2/6", speaker: "Local", context: "Take the blue line and change at Central Station.", cn: "我要在哪一站换乘？", en: "Which station do I need to change at?", alts: ["Where should I transfer?"], category: "交通问路", tag: "地铁换乘 · transfer" },
  { scene: "城市 · 地铁站", turn: "3/6", speaker: "You", context: "You need a ticket for today and tomorrow.", cn: "一日票多少钱？", en: "How much is a day pass?", alts: ["How much does a one-day pass cost?"], category: "交通问路", tag: "购买车票 · 询价" },
  { scene: "城市 · 公交站", turn: "4/6", speaker: "You", context: "A bus has just pulled in.", cn: "这趟公交车去机场吗？", en: "Does this bus go to the airport?", alts: ["Will this bus take me to the airport?"], category: "交通问路", tag: "公交出行 · 确认路线" },
  { scene: "城市 · 出租车", turn: "5/6", speaker: "Driver", context: "Where would you like to go?", cn: "请带我去这个地址。", en: "Please take me to this address.", alts: ["Could you take me to this address, please?"], category: "交通问路", tag: "出租车 · 说明目的地" },
  { scene: "城市 · 出租车", turn: "6/6", speaker: "You", context: "The traffic ahead looks very heavy.", cn: "大概需要多长时间到那里？", en: "About how long will it take to get there?", alts: ["Roughly how long does it take to get there?"], category: "交通问路", tag: "询问时间 · how long" },

  // 问路与城际出行
  { scene: "街头 · 问路", turn: "1/6", speaker: "You", context: "Your phone has no signal and you need directions.", cn: "你能告诉我最近的地铁站怎么走吗？", en: "Could you tell me how to get to the nearest subway station?", alts: ["Can you show me the way to the nearest metro station?"], category: "交通问路", tag: "问路 · 礼貌请求" },
  { scene: "街头 · 问路", turn: "2/6", speaker: "Local", context: "Go straight and turn right at the second traffic light.", cn: "走路过去远吗？", en: "Is it far from here on foot?", alts: ["Is it a long walk from here?"], category: "交通问路", tag: "距离 · on foot" },
  { scene: "火车站 · 售票处", turn: "3/6", speaker: "Clerk", context: "Where are you traveling to?", cn: "我想买一张去伦敦的单程票。", en: "I would like a one-way ticket to London.", alts: ["I want to buy a single ticket to London."], category: "交通问路", tag: "火车购票 · one-way ticket" },
  { scene: "火车站 · 售票处", turn: "4/6", speaker: "You", context: "You can leave in the morning or afternoon.", cn: "最早的一班车几点出发？", en: "What time does the earliest train leave?", alts: ["When does the first train depart?"], category: "交通问路", tag: "时刻表 · earliest" },
  { scene: "火车站 · 站台", turn: "5/6", speaker: "You", context: "The departure board has just changed.", cn: "去巴黎的火车在哪个站台？", en: "Which platform does the train to Paris leave from?", alts: ["What platform is the train to Paris on?"], category: "交通问路", tag: "站台 · leave from" },
  { scene: "租车柜台", turn: "6/6", speaker: "Staff", context: "Would you like the basic or full insurance?", cn: "全额保险包括哪些内容？", en: "What does the full insurance cover?", alts: ["What is included in the full insurance?"], category: "交通问路", tag: "租车 · 保险范围" },

  // 酒店入住与问题处理
  { scene: "酒店 · 前台入住", turn: "1/8", speaker: "Receptionist", context: "Welcome. How can I help you?", cn: "你好，我以王这个姓订了一间房。", en: "Hi, I have a reservation under the name Wang.", alts: ["Hello, I booked a room under the name Wang."], category: "酒店住宿", tag: "入住 · reservation under" },
  { scene: "酒店 · 前台入住", turn: "2/8", speaker: "Receptionist", context: "May I see your passport and a credit card?", cn: "可以。押金是多少？", en: "Sure. How much is the deposit?", alts: ["Of course. How much do I need to pay as a deposit?"], category: "酒店住宿", tag: "酒店押金 · deposit" },
  { scene: "酒店 · 前台入住", turn: "3/8", speaker: "Receptionist", context: "Breakfast is served from seven to ten.", cn: "早餐包含在房费里吗？", en: "Is breakfast included in the room rate?", alts: ["Does the room rate include breakfast?"], category: "酒店住宿", tag: "早餐 · be included" },
  { scene: "酒店 · 前台入住", turn: "4/8", speaker: "You", context: "You would like to explore before your room is ready.", cn: "我可以先把行李寄存在这里吗？", en: "Could I leave my luggage here for a while?", alts: ["Can you store my bags until my room is ready?"], category: "酒店住宿", tag: "寄存行李 · leave luggage" },
  { scene: "酒店 · 房间问题", turn: "5/8", speaker: "Receptionist", context: "Front desk. How may I help you?", cn: "房间里的空调好像坏了。", en: "The air conditioner in my room does not seem to be working.", alts: ["I think the air conditioning in my room is broken."], category: "酒店住宿", tag: "说明故障 · seem to" },
  { scene: "酒店 · 房间问题", turn: "6/8", speaker: "You", context: "The guests next door are still talking loudly after midnight.", cn: "隔壁太吵了，可以给我换个房间吗？", en: "The room next door is very noisy. Could I change rooms?", alts: ["It is too noisy next door. Could you move me to another room?"], category: "酒店住宿", tag: "更换房间 · noisy" },
  { scene: "酒店 · 客房服务", turn: "7/8", speaker: "Staff", context: "Housekeeping. What can I bring you?", cn: "可以再给我两条毛巾吗？", en: "Could I have two more towels, please?", alts: ["Could you bring me two extra towels, please?"], category: "酒店住宿", tag: "客房服务 · two more" },
  { scene: "酒店 · 退房", turn: "8/8", speaker: "Receptionist", context: "Did you enjoy your stay?", cn: "住得很好。我可以把行李寄存到下午吗？", en: "It was great. Could you keep my luggage until this afternoon?", alts: ["I had a great stay. Can I leave my bags here until this afternoon?"], category: "酒店住宿", tag: "退房 · 行李寄存" },

  // 餐厅完整点餐
  { scene: "餐厅 · 入座", turn: "1/10", speaker: "Host", context: "Good evening. Do you have a reservation?", cn: "没有。请问两个人有位置吗？", en: "No. Do you have a table for two?", alts: ["No, we do not. Is there a table available for two?"], category: "餐厅点餐", tag: "入座 · table for two" },
  { scene: "餐厅 · 入座", turn: "2/10", speaker: "Host", context: "Would you like to sit inside or outside?", cn: "如果可以的话，我们想坐在外面。", en: "We would like to sit outside, if possible.", alts: ["Outside, please, if there is a table available."], category: "餐厅点餐", tag: "选择座位 · if possible" },
  { scene: "餐厅 · 看菜单", turn: "3/10", speaker: "Server", context: "Here are your menus.", cn: "可以给我一份英文菜单吗？", en: "Could I have a menu in English, please?", alts: ["Do you have an English menu?"], category: "餐厅点餐", tag: "菜单 · 礼貌请求" },
  { scene: "餐厅 · 看菜单", turn: "4/10", speaker: "You", context: "There are several local dishes you do not recognize.", cn: "你最推荐哪一道菜？", en: "Which dish would you recommend?", alts: ["What dish do you recommend?"], category: "餐厅点餐", tag: "推荐菜 · recommend" },
  { scene: "餐厅 · 食物过敏", turn: "5/10", speaker: "You", context: "You need to make sure the dish is safe for you.", cn: "我对花生过敏，这道菜里有花生吗？", en: "I am allergic to peanuts. Does this dish contain any peanuts?", alts: ["I have a peanut allergy. Are there any peanuts in this dish?"], category: "餐厅点餐", tag: "饮食安全 · allergy" },
  { scene: "餐厅 · 点餐", turn: "6/10", speaker: "Server", context: "Are you ready to order?", cn: "我要烤鸡，配沙拉，不要薯条。", en: "I will have the grilled chicken with salad instead of fries.", alts: ["I would like the grilled chicken, with salad rather than fries."], category: "餐厅点餐", tag: "点餐 · instead of" },
  { scene: "餐厅 · 点餐", turn: "7/10", speaker: "Server", context: "How would you like your steak cooked?", cn: "五分熟，谢谢。", en: "Medium, please.", alts: ["I would like it medium, please."], category: "餐厅点餐", tag: "牛排熟度 · medium" },
  { scene: "餐厅 · 用餐中", turn: "8/10", speaker: "Server", context: "Is everything all right with your meal?", cn: "味道很好，不过这道菜有点凉了。", en: "It tastes great, but this dish is a little cold.", alts: ["It is delicious, but the dish is slightly cold."], category: "餐厅点餐", tag: "反馈问题 · a little" },
  { scene: "餐厅 · 结账", turn: "9/10", speaker: "You", context: "You and your friend are ready to leave.", cn: "麻烦买单，我们可以分开付吗？", en: "Could we have the bill, please? Can we pay separately?", alts: ["Could we get the check and split it, please?"], category: "餐厅点餐", tag: "结账 · split the bill" },
  { scene: "餐厅 · 结账", turn: "10/10", speaker: "Server", context: "Would you like a printed receipt?", cn: "要的，谢谢。服务费已经包含了吗？", en: "Yes, please. Is the service charge already included?", alts: ["Yes, thank you. Does the bill include the service charge?"], category: "餐厅点餐", tag: "账单 · service charge" },

  // 购物与日常生活
  { scene: "咖啡店", turn: "1/8", speaker: "Barista", context: "What can I get for you?", cn: "请给我一杯中杯拿铁，燕麦奶。", en: "Could I have a medium latte with oat milk, please?", alts: ["I would like a medium oat milk latte, please."], category: "购物生活", tag: "咖啡店 · 定制饮品" },
  { scene: "咖啡店", turn: "2/8", speaker: "Barista", context: "Is that for here or to go?", cn: "带走，谢谢。", en: "To go, please.", alts: ["Takeaway, please."], category: "购物生活", tag: "咖啡店 · to go" },
  { scene: "服装店", turn: "3/8", speaker: "Assistant", context: "Can I help you find anything?", cn: "我只是随便看看，谢谢。", en: "I am just looking, thank you.", alts: ["I am just browsing, thanks."], category: "购物生活", tag: "逛店 · just looking" },
  { scene: "服装店", turn: "4/8", speaker: "You", context: "The shirt you tried on is too tight.", cn: "这个有大一号的吗？", en: "Do you have this in a larger size?", alts: ["Is this available in a bigger size?"], category: "购物生活", tag: "尺码 · larger size" },
  { scene: "服装店", turn: "5/8", speaker: "You", context: "You want to see how the jacket fits.", cn: "我可以试穿一下吗？", en: "Can I try this on?", alts: ["Could I try it on?"], category: "购物生活", tag: "试穿 · try on" },
  { scene: "商店 · 付款", turn: "6/8", speaker: "Cashier", context: "Your total is thirty-two dollars.", cn: "我可以用信用卡付款吗？", en: "Can I pay by credit card?", alts: ["Do you accept credit cards?"], category: "购物生活", tag: "付款 · pay by" },
  { scene: "商店 · 退货", turn: "7/8", speaker: "Staff", context: "Is there anything wrong with the item?", cn: "它不太合适，我想退货。", en: "It does not fit very well, so I would like to return it.", alts: ["The fit is not right. I would like to return it."], category: "购物生活", tag: "退货 · return an item" },
  { scene: "公共场所", turn: "8/8", speaker: "You", context: "You have been looking for a restroom for several minutes.", cn: "不好意思，请问洗手间在哪里？", en: "Excuse me, where is the restroom?", alts: ["Sorry, could you tell me where the bathroom is?"], category: "购物生活", tag: "洗手间 · 必备表达" },

  // 看病、药房与紧急求助
  { scene: "诊所 · 挂号", turn: "1/6", speaker: "Receptionist", context: "What seems to be the problem?", cn: "我从昨天开始一直发烧。", en: "I have had a fever since yesterday.", alts: ["I have been running a fever since yesterday."], category: "医疗求助", tag: "症状 · 现在完成时" },
  { scene: "诊所 · 看诊", turn: "2/6", speaker: "Doctor", context: "Do you have any other symptoms?", cn: "我喉咙痛，而且有点咳嗽。", en: "I have a sore throat and a slight cough.", alts: ["My throat hurts and I have a little cough."], category: "医疗求助", tag: "描述症状 · sore throat" },
  { scene: "诊所 · 看诊", turn: "3/6", speaker: "Doctor", context: "Are you allergic to any medication?", cn: "我对青霉素过敏。", en: "I am allergic to penicillin.", alts: ["I have an allergy to penicillin."], category: "医疗求助", tag: "药物过敏 · allergic to" },
  { scene: "药房", turn: "4/6", speaker: "Pharmacist", context: "How can I help you?", cn: "请问有治晕车的药吗？", en: "Do you have anything for motion sickness?", alts: ["Do you have any medicine for travel sickness?"], category: "医疗求助", tag: "药房 · anything for" },
  { scene: "药房", turn: "5/6", speaker: "You", context: "You want to take the medicine correctly.", cn: "这个药一天要吃几次？", en: "How many times a day should I take this medicine?", alts: ["How often should I take this medication?"], category: "医疗求助", tag: "用药 · how often" },
  { scene: "街头 · 紧急情况", turn: "6/6", speaker: "You", context: "Someone nearby has fallen and needs immediate help.", cn: "请叫救护车！有人受伤了。", en: "Please call an ambulance! Someone is injured.", alts: ["Call an ambulance, please! Someone has been hurt."], category: "医疗求助", tag: "紧急求助 · ambulance" },

  // 社交与沟通修复
  { scene: "旅途中 · 初次见面", turn: "1/6", speaker: "Traveler", context: "Hi, is this seat taken?", cn: "没有，请坐。", en: "No, it is not. Please have a seat.", alts: ["No, go ahead. You can sit here."], category: "社交交流", tag: "初次见面 · 邀请入座" },
  { scene: "旅途中 · 闲聊", turn: "2/6", speaker: "Traveler", context: "Is this your first time here?", cn: "是的，我昨天刚到。", en: "Yes, it is. I just arrived yesterday.", alts: ["Yes. I only got here yesterday."], category: "社交交流", tag: "闲聊 · 刚刚到达" },
  { scene: "旅途中 · 闲聊", turn: "3/6", speaker: "Traveler", context: "How are you enjoying the city so far?", cn: "我很喜欢这里，大家都很友好。", en: "I really like it here. Everyone is very friendly.", alts: ["I am enjoying it a lot. People here are very friendly."], category: "社交交流", tag: "分享感受 · friendly" },
  { scene: "沟通修复", turn: "4/6", speaker: "Local", context: "The other person is speaking too quickly for you.", cn: "不好意思，你能说慢一点吗？", en: "Sorry, could you speak a little more slowly?", alts: ["Excuse me, can you speak a bit slower?"], category: "社交交流", tag: "听不清 · 请求放慢" },
  { scene: "沟通修复", turn: "5/6", speaker: "You", context: "You heard the words but did not understand the meaning.", cn: "我不太明白。你能换一种方式解释吗？", en: "I do not quite understand. Could you explain it in another way?", alts: ["I am not sure I understand. Can you say it another way?"], category: "社交交流", tag: "沟通修复 · explain" },
  { scene: "旅途中 · 告别", turn: "6/6", speaker: "Traveler", context: "It was lovely meeting you.", cn: "我也很高兴认识你。希望以后还能再见。", en: "It was nice meeting you too. I hope we meet again.", alts: ["It was great to meet you too. Hopefully we will see each other again."], category: "社交交流", tag: "告别 · nice meeting you" },

  // 租房、邻里与报修
  { scene: "公寓 · 看房签约", turn: "1/6", speaker: "Agent", context: "Would you like me to show you around the apartment?", cn: "好的。房租里包括水电费吗？", en: "Yes, please. Are utilities included in the rent?", alts: ["Yes, thank you. Does the rent include utilities?"], category: "住房邻里", tag: "租房 · utilities" },
  { scene: "公寓 · 看房签约", turn: "2/6", speaker: "Agent", context: "The lease is for twelve months.", cn: "如果我需要提前搬走怎么办？", en: "What happens if I need to move out early?", alts: ["What should I do if I have to leave before the lease ends?"], category: "住房邻里", tag: "租约 · 提前退租" },
  { scene: "公寓 · 搬入", turn: "3/6", speaker: "Manager", context: "Please let us know if you notice any problems.", cn: "厨房水槽漏水，可以派人来看看吗？", en: "The kitchen sink is leaking. Could someone come and take a look?", alts: ["There is a leak under the kitchen sink. Could you send someone to check it?"], category: "住房邻里", tag: "住房报修 · leak" },
  { scene: "公寓 · 报修", turn: "4/6", speaker: "Manager", context: "How urgent is the repair?", cn: "现在没有热水，所以比较着急。", en: "There is no hot water, so it is fairly urgent.", alts: ["We do not have any hot water, so I need it fixed quite urgently."], category: "住房邻里", tag: "报修 · 说明紧急程度" },
  { scene: "公寓 · 邻里沟通", turn: "5/6", speaker: "Neighbor", context: "Hi. Is everything all right?", cn: "不好意思，昨晚音乐有点大声，你可以调低一点吗？", en: "Sorry, the music was a little loud last night. Could you turn it down?", alts: ["Excuse me, the music was quite loud last night. Would you mind keeping it down?"], category: "住房邻里", tag: "邻里沟通 · turn down" },
  { scene: "公寓 · 收取包裹", turn: "6/6", speaker: "Neighbor", context: "I took in a package for you while you were out.", cn: "太感谢了。我晚一点过来拿可以吗？", en: "Thank you so much. Can I come by and pick it up later?", alts: ["Thanks a lot. Would it be okay if I collected it later?"], category: "住房邻里", tag: "邻里互助 · pick up" },

  // 银行、手机、邮寄与预约
  { scene: "城市 · 生活服务", turn: "1/6", speaker: "Bank clerk", context: "How can I help you today?", cn: "我想开一个账户，需要哪些材料？", en: "I would like to open an account. What documents do I need?", alts: ["I want to open a bank account. Which documents should I bring?"], category: "生活服务", tag: "银行 · 开户" },
  { scene: "城市 · 生活服务", turn: "2/6", speaker: "Mobile shop assistant", context: "Are you looking for a prepaid or monthly plan?", cn: "我只会待三个月，哪种套餐比较合适？", en: "I will only be here for three months. Which plan would be more suitable?", alts: ["I am staying for only three months. Which plan would you recommend?"], category: "生活服务", tag: "手机套餐 · suitable" },
  { scene: "城市 · 生活服务", turn: "3/6", speaker: "Postal clerk", context: "Where would you like to send the package?", cn: "我要寄到中国，大概需要多久？", en: "I would like to send it to China. About how long will it take?", alts: ["I need to mail this to China. Roughly how long does delivery take?"], category: "生活服务", tag: "邮寄 · delivery time" },
  { scene: "城市 · 生活服务", turn: "4/6", speaker: "Receptionist", context: "The earliest available appointment is next Tuesday.", cn: "下周二下午有空位吗？", en: "Is there an appointment available next Tuesday afternoon?", alts: ["Do you have any openings next Tuesday afternoon?"], category: "生活服务", tag: "预约 · available slot" },
  { scene: "城市 · 生活服务", turn: "5/6", speaker: "Delivery driver", context: "I am outside, but no one is answering the door.", cn: "我十分钟后到，可以请你等一下吗？", en: "I will be there in ten minutes. Could you wait for me?", alts: ["I am ten minutes away. Would you mind waiting?"], category: "生活服务", tag: "快递 · 请对方等待" },
  { scene: "城市 · 生活服务", turn: "6/6", speaker: "Customer service", context: "Could you describe the charge you do not recognize?", cn: "我的账单上有一笔重复扣费。", en: "There is a duplicate charge on my bill.", alts: ["I was charged twice for the same thing on my bill."], category: "生活服务", tag: "账单 · duplicate charge" },

  // 校园内与同学、老师交流
  { scene: "校园 · 课程与同学", turn: "1/6", speaker: "Classmate", context: "Hi, are you also taking Professor Miller's seminar?", cn: "是的，不过我错过了上周的课。你能把笔记发给我吗？", en: "Yes, but I missed last week's class. Could you send me your notes?", alts: ["Yes. I was absent last week. Would you mind sharing your notes with me?"], category: "校园交流", tag: "同学交流 · 借课堂笔记" },
  { scene: "校园 · 课程与同学", turn: "2/6", speaker: "Classmate", context: "Sure. We also formed groups for the presentation.", cn: "你们组还缺人吗？", en: "Do you still need another person in your group?", alts: ["Is there still room for one more person in your group?"], category: "校园交流", tag: "小组合作 · 加入小组" },
  { scene: "校园 · 课程与同学", turn: "3/6", speaker: "Classmate", context: "We are meeting in the library tomorrow afternoon.", cn: "好的，我几点过去比较合适？", en: "Great. What time should I come?", alts: ["Sounds good. What time would you like me to be there?"], category: "校园交流", tag: "安排时间 · should I come" },
  { scene: "校园 · 课堂提问", turn: "4/6", speaker: "Professor", context: "Does anyone have any questions about today's lecture?", cn: "您能再解释一下这个概念和上一个概念的区别吗？", en: "Could you explain the difference between this concept and the previous one again?", alts: ["Could you go over how this concept differs from the previous one?"], category: "校园交流", tag: "课堂提问 · explain the difference" },
  { scene: "校园 · 课后交流", turn: "5/6", speaker: "Professor", context: "I can talk for a few minutes after class.", cn: "我对作业要求不太确定，可以确认一下吗？", en: "I am not completely sure about the assignment requirements. Could I clarify them with you?", alts: ["I am a little unclear about the assignment. Could I check the requirements with you?"], category: "校园交流", tag: "课后请教 · clarify" },
  { scene: "校园 · 老师答疑", turn: "6/6", speaker: "Professor", context: "My office hours are on Thursday afternoon.", cn: "我可以周四三点去您的办公室吗？", en: "Could I come to your office at three on Thursday?", alts: ["Would it be okay if I came by your office at three on Thursday?"], category: "校园交流", tag: "office hours · 预约老师" },

  // 导师、组会与实验室沟通
  { scene: "研究组 · 导师会议", turn: "1/6", speaker: "Supervisor", context: "How has your analysis been progressing?", cn: "大部分已经完成，但验证结果还不稳定。", en: "Most of it is finished, but the validation results are still unstable.", alts: ["I have completed most of the analysis, but the validation results are not stable yet."], category: "科研沟通", tag: "进展汇报 · validation" },
  { scene: "研究组 · 导师会议", turn: "2/6", speaker: "Supervisor", context: "What do you think is causing the instability?", cn: "我怀疑是边界条件设置的问题。", en: "I suspect that the boundary conditions may be causing the problem.", alts: ["I think the issue may come from how the boundary conditions are set."], category: "科研沟通", tag: "机理判断 · suspect" },
  { scene: "研究组 · 导师会议", turn: "3/6", speaker: "Supervisor", context: "What are you planning to try next?", cn: "我会先做一次敏感性分析，然后重新校准模型。", en: "I will run a sensitivity analysis first and then recalibrate the model.", alts: ["My next step is to perform a sensitivity analysis before recalibrating the model."], category: "科研沟通", tag: "研究计划 · sensitivity analysis" },
  { scene: "研究组 · 导师会议", turn: "4/6", speaker: "Supervisor", context: "That sounds reasonable. When can you share the new results?", cn: "如果没有新的问题，我可以在周五前发给您。", en: "If no new issues come up, I can send them to you by Friday.", alts: ["I should be able to share them by Friday unless another issue arises."], category: "科研沟通", tag: "承诺时间 · by Friday" },
  { scene: "研究组 · 组会讨论", turn: "5/6", speaker: "Lab member", context: "I noticed that one of the figures uses a different scale.", cn: "谢谢你指出来。我会统一所有图的坐标范围。", en: "Thanks for pointing that out. I will use the same axis range for all the figures.", alts: ["Thank you for catching that. I will make the axis ranges consistent across the figures."], category: "科研沟通", tag: "接受建议 · point out" },
  { scene: "研究组 · 组会讨论", turn: "6/6", speaker: "Lab member", context: "Would you like me to review the revised code?", cn: "太好了。我更新完共享仓库后告诉你。", en: "That would be great. I will let you know after I update the shared repository.", alts: ["That would be very helpful. I will message you once the shared repository is updated."], category: "科研沟通", tag: "协作 · shared repository" },

  // 国际会议注册、交流与建立联系
  { scene: "国际会议 · 注册与交流", turn: "1/6", speaker: "Registration staff", context: "Welcome. May I have your name and affiliation?", cn: "我叫王明，来自中山大学。", en: "My name is Ming Wang, and I am from Sun Yat-sen University.", alts: ["I am Ming Wang from Sun Yat-sen University."], category: "学术会议", tag: "会议注册 · affiliation" },
  { scene: "国际会议 · 注册与交流", turn: "2/6", speaker: "Registration staff", context: "Here is your badge and conference program.", cn: "谢谢。海报展示区在哪里？", en: "Thank you. Where is the poster exhibition area?", alts: ["Thanks. Could you tell me where the poster hall is?"], category: "学术会议", tag: "会议问路 · poster hall" },
  { scene: "国际会议 · 茶歇交流", turn: "3/6", speaker: "Researcher", context: "Hi, I enjoyed your poster. What is your research about?", cn: "我研究的是新污染物在多介质环境中的迁移。", en: "My research focuses on the transport of emerging contaminants across multiple environmental media.", alts: ["I study how emerging contaminants move through different environmental media."], category: "学术会议", tag: "介绍研究 · focuses on" },
  { scene: "国际会议 · 茶歇交流", turn: "4/6", speaker: "Researcher", context: "That is very relevant to our current project.", cn: "很高兴听到这个。也许我们可以交流一下数据和方法。", en: "I am glad to hear that. Perhaps we could exchange ideas about our data and methods.", alts: ["That is great to hear. Maybe we could discuss our datasets and methods."], category: "学术会议", tag: "建立合作 · exchange ideas" },
  { scene: "国际会议 · 茶歇交流", turn: "5/6", speaker: "Researcher", context: "Absolutely. Are you on LinkedIn?", cn: "在的。我也可以把邮箱发给你。", en: "Yes, I am. I can also give you my email address.", alts: ["Yes. I can share my email with you as well."], category: "学术会议", tag: "交换联系方式 · contact details" },
  { scene: "国际会议 · 茶歇交流", turn: "6/6", speaker: "Researcher", context: "It was great talking with you.", cn: "我也很高兴。会后我会发邮件跟进。", en: "It was great talking with you too. I will follow up by email after the conference.", alts: ["Likewise. I will send you a follow-up email after the conference."], category: "学术会议", tag: "会后跟进 · follow up" },

  // 国际会议报告与问答
  { scene: "国际会议 · 口头报告", turn: "1/6", speaker: "Session chair", context: "You may begin when you are ready.", cn: "谢谢主席。今天我将介绍我们最近的研究工作。", en: "Thank you, Chair. Today I will present our recent research.", alts: ["Thank you, Chair. I would like to present our latest work today."], category: "学术会议", tag: "报告开场 · session chair" },
  { scene: "国际会议 · 口头报告", turn: "2/6", speaker: "You", context: "You are moving from the background to the main research question.", cn: "我们的研究主要回答两个问题。", en: "Our study addresses two main questions.", alts: ["This study aims to answer two main questions."], category: "学术会议", tag: "研究问题 · address" },
  { scene: "国际会议 · 口头报告", turn: "3/6", speaker: "You", context: "You are showing the most important result on the slide.", cn: "这里最重要的发现是模型在独立数据上仍然表现稳定。", en: "The key finding here is that the model remains robust on independent data.", alts: ["Most importantly, the model still performs reliably on an independent dataset."], category: "学术会议", tag: "报告结果 · key finding" },
  { scene: "国际会议 · 问答", turn: "4/6", speaker: "Audience member", context: "How did you account for uncertainty in the input data?", cn: "谢谢您的问题。我们通过蒙特卡洛模拟传播输入不确定性。", en: "Thank you for the question. We propagated the input uncertainty using Monte Carlo simulation.", alts: ["Thank you. We used Monte Carlo simulation to propagate uncertainty in the inputs."], category: "学术会议", tag: "会议问答 · uncertainty" },
  { scene: "国际会议 · 问答", turn: "5/6", speaker: "Audience member", context: "Could the same method be applied at a global scale?", cn: "原则上可以，但还需要更高分辨率的排放数据。", en: "In principle, yes, but higher-resolution emission data would be needed.", alts: ["Potentially, yes. However, it would require emission data at a higher resolution."], category: "学术会议", tag: "谨慎回答 · in principle" },
  { scene: "国际会议 · 问答", turn: "6/6", speaker: "Session chair", context: "We have time for one final comment.", cn: "如果您愿意，我们可以在会后继续讨论这个问题。", en: "If you would like, we can continue this discussion after the session.", alts: ["I would be happy to discuss this further with you after the session."], category: "学术会议", tag: "结束问答 · further discussion" }
];
